version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"  # Host:Container
    environment:
      MONGO_INITDB_ROOT_USERNAME: trevyro
      MONGO_INITDB_ROOT_PASSWORD: trevyro@123#
      MONGO_INITDB_DATABASE: trevyro
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
